# Generated by Django 3.2.7 on 2021-09-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkMenuItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SOFT', 'Soft drink'), ('HOT', 'Hot drink'), ('BEER', 'Beer'), ('WHITE_WINE', 'White wine'), ('RED_WINE', 'Red wine'), ('CAKTAIL', 'Caktail'), ('SAKE', 'Sake'), ('OTHER', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('runout', models.BooleanField(default=False)),
                ('sulpher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMenuItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TAPAS', 'Tapas'), ('NOODLE', 'Noodle'), ('RICE', 'Rice')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('runout', models.BooleanField(default=False)),
                ('glueten_free', models.BooleanField(default=False)),
                ('glueten_free_option', models.BooleanField(default=False)),
                ('sesame', models.BooleanField(default=False)),
                ('soybeans', models.BooleanField(default=False)),
                ('nuts', models.BooleanField(default=False)),
                ('peanuts', models.BooleanField(default=False)),
                ('mustard', models.BooleanField(default=False)),
            ],
        ),
    ]
