# Generated by Django 3.2.7 on 2021-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkmenuitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
