# Generated by Django 3.2.7 on 2021-09-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210927_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenuitem',
            name='category',
            field=models.CharField(choices=[('SOFT', 'Soft drink'), ('HOT', 'Hot drink'), ('BEER', 'Beer'), ('WHITE WINE', 'White wine'), ('RED WINE', 'Red wine'), ('COCKTAIL', 'Cocktail'), ('SAKE', 'Sake'), ('OTHER', 'Other'), ('SPECIAL', 'Special')], max_length=50),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='category',
            field=models.CharField(choices=[('TAPAS', 'Tapas'), ('DESERT', 'Desert'), ('SPECIAL', 'Special')], max_length=50),
        ),
    ]
