# Generated by Django 3.2.7 on 2021-10-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20211001_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenuitem',
            name='category',
            field=models.CharField(choices=[('Soft drink', 'Soft drink'), ('HOT', 'Hot drink'), ('BEER', 'Beer'), ('WHITE WINE', 'White wine'), ('RED WINE', 'Red wine'), ('COCKTAIL', 'Cocktail'), ('SAKE', 'Sake'), ('OTHER', 'Other'), ('SPECIAL', 'Special')], max_length=50),
        ),
    ]
