# Generated by Django 3.2.7 on 2021-10-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_drinkmenuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenuitem',
            name='onion_garlic_free_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drinkmenuitem',
            name='category',
            field=models.CharField(choices=[('SOFT DRINK', 'Soft drink'), ('HOT DRINK', 'Hot drink'), ('BEER', 'Beer'), ('WHITE WINE', 'White wine'), ('RED WINE', 'Red wine'), ('COCKTAIL', 'Cocktail'), ('SAKE', 'Sake'), ('OTHER', 'Other'), ('SPECIAL', 'Special')], max_length=50),
        ),
    ]
